function print_simulation_tables(scenarios, sample_results, max_rows)
%PRINT_SIMULATION_TABLES Print sample patient-level simulation tables.

fprintf('\n%s\n', repeat_char('=', 120));
fprintf(' Simulation Tables / Sample Patient Records\n');
fprintf('%s\n', repeat_char('=', 120));
fprintf(' Showing %d patient records from the 4-doctor priority model.\n', max_rows);

for s = 1:length(scenarios)
    result = sample_results{s};
    row_count = min(max_rows, result.total_arrivals);

    fprintf('\nScenario: %s\n', scenarios{s});
    fprintf('%s\n', repeat_char('-', 120));
    fprintf(' %-3s %7s %7s %7s %6s %7s %3s %7s %7s %7s %7s %7s %7s %3s\n', ...
        'n', 'RN-IAT', 'IAT', 'Arrive', 'Lambda', 'RN-Pri', 'Pri', ...
        'RN-Svc', 'Svc', 'Begin', 'End', 'Wait', 'Spend', 'Doc');
    fprintf('%s\n', repeat_char('-', 120));

    for i = 1:row_count
        fprintf(' %-3d %7.4f %7.2f %7.2f %6.3f %7.4f %3d %7.4f %7.2f %7.2f %7.2f %7.2f %7.2f %3d\n', ...
            i, ...
            result.rn_interarrival(i), ...
            result.inter_arrival_times(i), ...
            result.arrival_times(i), ...
            result.arrival_lambdas(i), ...
            result.rn_priority(i), ...
            result.priorities(i), ...
            result.rn_service(i), ...
            result.service_times(i), ...
            result.service_start_times(i), ...
            result.service_end_times(i), ...
            result.waiting_times(i), ...
            result.time_in_system(i), ...
            result.assigned_doctors(i));
    endfor

    fprintf('%s\n', repeat_char('-', 120));
    fprintf(' Full patient table saved to results/priority_model_simulation_table.csv\n');
endfor

endfunction
