function write_summary_csv(file_path, scenarios, rows)
%WRITE_SUMMARY_CSV Write scenario-level mean metrics with scenario names.

fid = fopen(file_path, 'w');
if fid < 0
    error('Could not open summary output file.');
endif

fprintf(fid, 'scenario,total_arrivals,patients_served_within_shift,average_waiting_time,average_queue_length,average_time_in_system,probability_waiting,doctor_utilization,total_simulation_time,last_departure_time,avg_wait_priority_1,avg_wait_priority_2,avg_wait_priority_3\n');

for i = 1:size(rows, 1)
    fprintf(fid, '%s,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f\n', ...
        scenarios{i}, ...
        rows(i, 1), ...
        rows(i, 2), ...
        rows(i, 3), ...
        rows(i, 4), ...
        rows(i, 5), ...
        rows(i, 6), ...
        rows(i, 7), ...
        rows(i, 8), ...
        rows(i, 9), ...
        rows(i, 10), ...
        rows(i, 11), ...
        rows(i, 12));
endfor

fclose(fid);

endfunction
