function write_patient_csv(file_path, result)
%WRITE_PATIENT_CSV Write one replication's patient-level simulation table.

fid = fopen(file_path, 'w');
if fid < 0
    error('Could not open patient output file.');
endif

fprintf(fid, 'patient,arrival_time,priority,service_time,service_start_time,waiting_time,service_end_time,time_in_system,assigned_doctor,served_within_shift\n');

for i = 1:result.total_arrivals
    served_within_shift = result.service_end_times(i) <= result.simulation_horizon;
    fprintf(fid, '%d,%.6f,%d,%.6f,%.6f,%.6f,%.6f,%.6f,%d,%d\n', ...
        i, ...
        result.arrival_times(i), ...
        result.priorities(i), ...
        result.service_times(i), ...
        result.service_start_times(i), ...
        result.waiting_times(i), ...
        result.service_end_times(i), ...
        result.time_in_system(i), ...
        result.assigned_doctors(i), ...
        served_within_shift);
endfor

fclose(fid);

endfunction
